/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Character } from "./Character";
import { CharacterCountArgs } from "./CharacterCountArgs";
import { CharacterFindManyArgs } from "./CharacterFindManyArgs";
import { CharacterFindUniqueArgs } from "./CharacterFindUniqueArgs";
import { CreateCharacterArgs } from "./CreateCharacterArgs";
import { UpdateCharacterArgs } from "./UpdateCharacterArgs";
import { DeleteCharacterArgs } from "./DeleteCharacterArgs";
import { StatusFindManyArgs } from "../../status/base/StatusFindManyArgs";
import { Status } from "../../status/base/Status";
import { User } from "../../user/base/User";
import { CharacterDto } from "../CharacterDto";
import { CharacterService } from "../character.service";
@graphql.Resolver(() => Character)
export class CharacterResolverBase {
  constructor(protected readonly service: CharacterService) {}

  async _charactersMeta(
    @graphql.Args() args: CharacterCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Character])
  async characters(
    @graphql.Args() args: CharacterFindManyArgs
  ): Promise<Character[]> {
    return this.service.characters(args);
  }

  @graphql.Query(() => Character, { nullable: true })
  async character(
    @graphql.Args() args: CharacterFindUniqueArgs
  ): Promise<Character | null> {
    const result = await this.service.character(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Character)
  async createCharacter(
    @graphql.Args() args: CreateCharacterArgs
  ): Promise<Character> {
    return await this.service.createCharacter({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Character)
  async updateCharacter(
    @graphql.Args() args: UpdateCharacterArgs
  ): Promise<Character | null> {
    try {
      return await this.service.updateCharacter({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Character)
  async deleteCharacter(
    @graphql.Args() args: DeleteCharacterArgs
  ): Promise<Character | null> {
    try {
      return await this.service.deleteCharacter(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Status], { name: "statuses" })
  async findStatuses(
    @graphql.Parent() parent: Character,
    @graphql.Args() args: StatusFindManyArgs
  ): Promise<Status[]> {
    const results = await this.service.findStatuses(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Character): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CharacterDto)
  async RaiseCharacterLevel(
    @graphql.Args()
    args: CharacterDto
  ): Promise<CharacterDto> {
    return this.service.RaiseCharacterLevel(args);
  }
}
