/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Monster } from "./Monster";
import { MonsterCountArgs } from "./MonsterCountArgs";
import { MonsterFindManyArgs } from "./MonsterFindManyArgs";
import { MonsterFindUniqueArgs } from "./MonsterFindUniqueArgs";
import { CreateMonsterArgs } from "./CreateMonsterArgs";
import { UpdateMonsterArgs } from "./UpdateMonsterArgs";
import { DeleteMonsterArgs } from "./DeleteMonsterArgs";
import { FieldModel } from "../../fieldModel/base/FieldModel";
import { MonsterDto } from "../MonsterDto";
import { MonsterService } from "../monster.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Monster)
export class MonsterResolverBase {
  constructor(
    protected readonly service: MonsterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Monster",
    action: "read",
    possession: "any",
  })
  async _monstersMeta(
    @graphql.Args() args: MonsterCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Monster])
  @nestAccessControl.UseRoles({
    resource: "Monster",
    action: "read",
    possession: "any",
  })
  async monsters(
    @graphql.Args() args: MonsterFindManyArgs
  ): Promise<Monster[]> {
    return this.service.monsters(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Monster, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Monster",
    action: "read",
    possession: "own",
  })
  async monster(
    @graphql.Args() args: MonsterFindUniqueArgs
  ): Promise<Monster | null> {
    const result = await this.service.monster(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Monster)
  @nestAccessControl.UseRoles({
    resource: "Monster",
    action: "create",
    possession: "any",
  })
  async createMonster(
    @graphql.Args() args: CreateMonsterArgs
  ): Promise<Monster> {
    return await this.service.createMonster({
      ...args,
      data: {
        ...args.data,

        fieldField: args.data.fieldField
          ? {
              connect: args.data.fieldField,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Monster)
  @nestAccessControl.UseRoles({
    resource: "Monster",
    action: "update",
    possession: "any",
  })
  async updateMonster(
    @graphql.Args() args: UpdateMonsterArgs
  ): Promise<Monster | null> {
    try {
      return await this.service.updateMonster({
        ...args,
        data: {
          ...args.data,

          fieldField: args.data.fieldField
            ? {
                connect: args.data.fieldField,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Monster)
  @nestAccessControl.UseRoles({
    resource: "Monster",
    action: "delete",
    possession: "any",
  })
  async deleteMonster(
    @graphql.Args() args: DeleteMonsterArgs
  ): Promise<Monster | null> {
    try {
      return await this.service.deleteMonster(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => FieldModel, {
    nullable: true,
    name: "fieldField",
  })
  @nestAccessControl.UseRoles({
    resource: "FieldModel",
    action: "read",
    possession: "any",
  })
  async getFieldField(
    @graphql.Parent() parent: Monster
  ): Promise<FieldModel | null> {
    const result = await this.service.getFieldField(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MonsterDto)
  async FightMonster(
    @graphql.Args()
    args: MonsterDto
  ): Promise<MonsterDto> {
    return this.service.FightMonster(args);
  }
}
