/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { StatusService } from "../status.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StatusCreateInput } from "./StatusCreateInput";
import { Status } from "./Status";
import { StatusFindManyArgs } from "./StatusFindManyArgs";
import { StatusWhereUniqueInput } from "./StatusWhereUniqueInput";
import { StatusUpdateInput } from "./StatusUpdateInput";
import { StatusDto } from "../StatusDto";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StatusControllerBase {
  constructor(
    protected readonly service: StatusService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Status })
  @nestAccessControl.UseRoles({
    resource: "Status",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: StatusCreateInput,
  })
  async createStatus(@common.Body() data: StatusCreateInput): Promise<Status> {
    return await this.service.createStatus({
      data: {
        ...data,

        character: data.character
          ? {
              connect: data.character,
            }
          : undefined,
      },
      select: {
        agility: true,

        character: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        intelligence: true,
        strength: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Status] })
  @ApiNestedQuery(StatusFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Status",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async statuses(@common.Req() request: Request): Promise<Status[]> {
    const args = plainToClass(StatusFindManyArgs, request.query);
    return this.service.statuses({
      ...args,
      select: {
        agility: true,

        character: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        intelligence: true,
        strength: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Status })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Status",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async status(
    @common.Param() params: StatusWhereUniqueInput
  ): Promise<Status | null> {
    const result = await this.service.status({
      where: params,
      select: {
        agility: true,

        character: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        intelligence: true,
        strength: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Status })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Status",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: StatusUpdateInput,
  })
  async updateStatus(
    @common.Param() params: StatusWhereUniqueInput,
    @common.Body() data: StatusUpdateInput
  ): Promise<Status | null> {
    try {
      return await this.service.updateStatus({
        where: params,
        data: {
          ...data,

          character: data.character
            ? {
                connect: data.character,
              }
            : undefined,
        },
        select: {
          agility: true,

          character: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          intelligence: true,
          strength: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Status })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Status",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteStatus(
    @common.Param() params: StatusWhereUniqueInput
  ): Promise<Status | null> {
    try {
      return await this.service.deleteStatus({
        where: params,
        select: {
          agility: true,

          character: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          intelligence: true,
          strength: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Post("/update-status")
  @swagger.ApiOkResponse({
    type: StatusDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async UpdateStatus(
    @common.Body()
    body: StatusDto
  ): Promise<StatusDto> {
    return this.service.UpdateStatus(body);
  }
}
